// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Aggiungiamo isLoggedIn bool
func Layout(title string, isLoggedIn bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"it\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><link rel=\"stylesheet\" href=\"/dist/style.css\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/layout.templ`, Line: 11, Col: 22}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</title></head><body class=\"bg-amber-100 text-gray-900 font-sans selection:bg-pink-400 selection:text-black\"><header class=\"flex flex-wrap sm:justify-start sm:flex-nowrap w-full py-4 bg-white border-b-4 border-black sticky top-0 z-50\"><nav class=\"max-w-[85rem] w-full mx-auto px-4 sm:px-6 flex flex-wrap basis-full items-center justify-between\"><a class=\"sm:order-1 flex-none text-2xl font-black uppercase tracking-tighter bg-yellow-300 px-3 py-1 border-2 border-black -rotate-2 hover:rotate-0 transition-transform shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]\" href=\"/\">Task Manager</a><div class=\"sm:order-3 flex items-center gap-x-4\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if isLoggedIn {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<form action=\"/logout\" method=\"POST\" class=\"inline\"><button type=\"submit\" class=\"py-2 px-6 inline-flex items-center text-sm font-black uppercase bg-red-500 border-2 border-black text-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:translate-y-1 hover:translate-x-1 hover:shadow-none transition-all\">Logout</button></form>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<a href=\"/login\" class=\"py-2 px-6 inline-flex items-center text-sm font-black uppercase bg-white border-2 border-black text-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:bg-pink-400 hover:translate-y-1 hover:translate-x-1 hover:shadow-none transition-all\">Login</a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div><div id=\"hs-navbar-alignment\" class=\"hs-collapse hidden overflow-hidden transition-all duration-300 basis-full grow sm:grow-0 sm:basis-auto sm:block sm:order-2\"><div class=\"flex flex-col gap-4 mt-6 sm:flex-row sm:items-center sm:mt-0 sm:ps-8\"><a class=\"text-sm font-black uppercase px-3 py-2 border-2 border-transparent hover:border-black hover:bg-cyan-300 transition-all\" href=\"/\">Landing</a> <a class=\"text-sm font-black uppercase px-3 py-2 border-2 border-transparent hover:border-black hover:bg-cyan-300 transition-all\" href=\"/dashboard\">Dashboard</a> <a class=\"text-sm font-black uppercase px-3 py-2 border-2 border-transparent hover:border-black hover:bg-cyan-300 transition-all\" href=\"/work\">Work</a> <a class=\"text-sm font-black uppercase px-3 py-2 border-2 border-transparent hover:border-black hover:bg-cyan-300 transition-all\" href=\"/profile\">Profile</a></div></div></nav></header><main class=\"min-h-screen\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</main></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
